### ISSUE TITLE
Missing sshpass

### ISSUE THREAD

**Issue by jseguillon** [jseguillon/winspray#14]
```
PS C:\temp\2> cat .\test.yml
servers:
  - name: k8s-server-1
    roles:
      - etcd
      - master
      - node
    cpu: 2
    memMin: 2048
    memMax: 4096
    vagrantBox: "generic/centos8"
  - name: k8s-server-2
    roles:
      - node
    cpu: 2
    memMin: 2048
    memMax: 4096
    vagrantBox: "generic/debian10"

PS C:\temp\2> New-Winspray-Cluster .\test.yml -Force



TASK [download : prep_kubeadm_images | Create kubeadm config] ******************************************
changed: [k8s-server-1.mshome.net]
Friday 19 June 2020  12:01:36 +0000 (0:00:00.682)       0:05:04.773 ***********

TASK [download : prep_kubeadm_images | Copy kubeadm binary from download dir to system path] ***********
fatal: [k8s-server-1.mshome.net -> k8s-server-1.mshome.net]: FAILED! => {"changed": false, "cmd": "sshpass", "msg": "[Errno 2] No such file or directory: b'sshpass': b'sshpass'", "rc": 2}

NO MORE HOSTS LEFT *************************************************************************************

```

```
    k8s-server-1: Ok for ssh with password
    k8s-server-1: kubernetes == no swap
    k8s-server-1: k8s = no fw unless prod
    k8s-server-1: Removed /etc/systemd/system/multi-user.target.wants/firewalld.service.
    k8s-server-1: Removed /etc/systemd/system/dbus-org.fedoraproject.FirewallD1.service.
    k8s-server-1: Installing anible required packages
    k8s-server-1: CentOS-8 - AppStream                            1.4 MB/s | 5.8 MB     00:04
    k8s-server-1: CentOS-8 - Base                                 1.7 MB/s | 2.2 MB     00:01
    k8s-server-1: CentOS-8 - Extras                                15 kB/s | 6.7 kB     00:00
    k8s-server-1: Extra Packages for Enterprise Linux Modular 8 - 0.0  B/s |   0  B     00:30
    k8s-server-1: Failed to download metadata for repo 'epel-modular'
    k8s-server-1: Error: Failed to download metadata for repo 'epel-modular'
    k8s-server-1: /tmp/vagrant-shell: line 11: apt-get: command not found
    k8s-server-1: Centos 8 tweak - sets a default python for ansible
    k8s-server-1: CENTOS_MANTISBT_PROJECT="CentOS-8"
    k8s-server-1: Centos-8 tweak - control plane interface disabled until activated from ansible
    k8s-server-1: CENTOS_MANTISBT_PROJECT="CentOS-8"
    k8s-server-1: Done
```

**Comment by jseguillon** [comment]
while 
```
   k8s-server-2: Failed to disable unit: Unit file firewalld.service does not exist.
    k8s-server-2: Installing anible required packages
    k8s-server-2: /tmp/vagrant-shell: line 11: yum: command not found
    k8s-server-2: Reading package lists...
    k8s-server-2: Building dependency tree...
    k8s-server-2:
    k8s-server-2: Reading state information...
    k8s-server-2: The following NEW packages will be installed:
    k8s-server-2:   sshpass
    k8s-server-2: 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
    k8s-server-2: Need to get 11.3 kB of archives.
    k8s-server-2: After this operation, 31.7 kB of additional disk space will be used.
    k8s-server-2: Get:1 http://deb.debian.org/debian buster/main amd64 sshpass amd64 1.06-1 [11.3 kB]
    k8s-server-2: dpkg-preconfigure: unable to re-open stdin: No such file or directory
    k8s-server-2: Fetched 11.3 kB in 0s (115 kB/s)
    k8s-server-2: Selecting previously unselected package sshpass.
```
